# Evaluating hyperparameter tuning results

In [5]:
import pandas as pd

adult_census = pd.read_csv("datasets/adult-census.csv")
target_name = "class"

target = adult_census[target_name]
data = adult_census.drop(columns=[target_name, "education-num"])

In [6]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import make_column_selector as selector

categorical_columns_selector = selector(dtype_include=object)
categorical_columns = categorical_columns_selector(data)

categorical_preprocessor = OrdinalEncoder(
    handle_unknown="use_encoded_value", unknown_value=-1
)
preprocessor = make_column_transformer(
    (categorical_preprocessor, categorical_columns),
    remainder="passthrough",
)

In [7]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.pipeline import Pipeline

model = Pipeline(
    [
        ("preprocessor", preprocessor),
        (
            "classifier",
            HistGradientBoostingClassifier(random_state=42, max_leaf_nodes=4),
        ),
    ]
)

In [8]:
from sklearn.model_selection import cross_validate

cv_results = cross_validate(model, data, target, cv=5)
cv_results = pd.DataFrame(cv_results)
cv_results

   fit_time  score_time  test_score
0  0.189019    0.025899    0.863241
1  0.177574    0.022165    0.860784
2  0.162015    0.022786    0.860360
3  0.158650    0.022995    0.862408
4  0.157184    0.022340    0.866912

In [9]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(
    data, target, test_size=0.2, random_state=42,
)

In [10]:
cv_results = cross_validate(model, data_train, target_train)
cv_results = pd.DataFrame(cv_results)
cv_results

   fit_time  score_time  test_score
0  0.172880    0.027301    0.862188
1  0.176982    0.027332    0.859757
2  0.162167    0.020570    0.864491
3  0.138018    0.019481    0.859867
4  0.145603    0.022757    0.860379

In [11]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "classifier__learning_rate": (0.05, 0.5),
    "classifier__max_leaf_nodes": (10, 30),
}

model_grid_search = GridSearchCV(model, param_grid=param_grid, n_jobs=2, cv=2)

In [14]:
cv_results = cross_validate(
    model_grid_search, data, target, cv=5, n_jobs=2, return_estimator=True,
)

In [15]:
for estimator in cv_results["estimator"]:
    print(estimator.best_params_)

{'classifier__learning_rate': 0.05, 'classifier__max_leaf_nodes': 30}
{'classifier__learning_rate': 0.05, 'classifier__max_leaf_nodes': 30}
{'classifier__learning_rate': 0.05, 'classifier__max_leaf_nodes': 30}
{'classifier__learning_rate': 0.05, 'classifier__max_leaf_nodes': 30}
{'classifier__learning_rate': 0.05, 'classifier__max_leaf_nodes': 30}

In [13]:
cv_results = pd.DataFrame(cv_results)
cv_results

    fit_time  score_time  test_score
0  15.982412    0.055427    0.868666
1  16.219131    0.038129    0.869280
2   2.930132    0.040354    0.870188
3   2.854984    0.044261    0.872441
4   1.869240    0.030048    0.874898

In [16]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

data, target = fetch_california_housing(return_X_y=True, as_frame=True)
target *= 100

In [17]:
target

0        452.6
1        358.5
2        352.1
3        341.3
4        342.2
         ...
20635     78.1
20636     77.1
20637     92.3
20638     84.7
20639     89.4
Name: MedHouseVal, Length: 20640, dtype: float64

In [18]:
data_train, data_test, target_train, target_test = train_test_split(
    data, target, random_state=42,
)

In [19]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

scaler = StandardScaler()

model = make_pipeline(
    scaler,
    KNeighborsRegressor(),
)

In [20]:
data.dtypes

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
dtype: object

In [22]:
import numpy as np

from sklearn.model_selection import RandomizedSearchCV

In [27]:
param_distributions = {
    "kneighborsregressor__n_neighbors": np.logspace(0, 3, num=10).astype(np.int32),
    "standardscaler__with_mean": [True, False],
    "standardscaler__with_std": [True, False],
}

In [32]:
model_random_search = RandomizedSearchCV(
    model,
    param_distributions=param_distributions,
    scoring="neg_mean_absolute_error",
    n_iter=20,
    n_jobs=2,
    verbose=0,
    random_state=1,
)

In [33]:
model_random_search.fit(data_train, target_train)

RandomizedSearchCV(estimator=Pipeline(steps=[('standardscaler',
                                              StandardScaler()),
                                             ('kneighborsregressor',
                                              KNeighborsRegressor())]),
                   n_iter=20, n_jobs=2,
                   param_distributions={'kneighborsregressor__n_neighbors': array([   1,    2,    4,   10,   21,   46,  100,  215,  464, 1000],
      dtype=int32),
                                        'standardscaler__with_mean': [True,
                                                                      False],
                                        'standardscaler__with_std': [True,
                                                                     False]},
                   random_state=1, scoring='neg_mean_absolute_error')

In [31]:
model_random_search.best_params_

{'standardscaler__with_std': True,
 'standardscaler__with_mean': False,
 'kneighborsregressor__n_neighbors': np.int32(10)}

In [35]:
pd.DataFrame(model_random_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_standardscaler__with_std,param_standardscaler__with_mean,param_kneighborsregressor__n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010973,0.000930,0.068833,0.004385,True,False,1,"{'standardscaler__with_std': True, 'standardsc...",-54.775433,-52.588055,-51.359477,-54.828945,-54.631928,-53.636768,1.413792,8
1,0.009719,0.000369,0.066618,0.001286,False,False,215,"{'standardscaler__with_std': False, 'standards...",-91.235919,-88.534179,-91.052123,-90.055153,-90.265650,-90.228605,0.958687,15
2,0.009782,0.000996,0.007853,0.000581,False,False,1,"{'standardscaler__with_std': False, 'standards...",-95.634328,-94.598343,-97.549545,-96.254873,-98.507431,-96.508904,1.382512,20
3,0.009365,0.000391,0.021488,0.003280,False,True,46,"{'standardscaler__with_std': False, 'standards...",-88.821845,-86.048962,-88.889881,-87.346337,-87.225100,-87.666425,1.071938,13
4,0.008770,0.000296,0.031023,0.000213,False,False,100,"{'standardscaler__with_std': False, 'standards...",-90.309987,-87.628587,-90.318812,-89.107234,-89.094267,-89.291777,0.993058,14
5,0.008811,0.000203,0.059843,0.000561,False,True,215,"{'standardscaler__with_std': False, 'standards...",-91.235919,-88.534179,-91.052123,-90.055153,-90.265650,-90.228605,0.958687,15
6,0.009497,0.000774,0.169786,0.014068,True,False,46,"{'standardscaler__with_std': True, 'standardsc...",-48.872857,-45.568601,-45.677369,-46.785742,-47.428248,-46.866563,1.220338,3
7,0.009338,0.000925,0.290640,0.010515,False,False,1000,"{'standardscaler__with_std': False, 'standards...",-92.038302,-89.381648,-91.957675,-91.002378,-91.506284,-91.177257,0.970928,19
8,0.009003,0.000238,0.013560,0.000385,False,False,21,"{'standardscaler__with_std': False, 'standards...",-86.690837,-83.375163,-86.128416,-84.837293,-85.112294,-85.228801,1.144525,11
9,0.009275,0.000256,0.217335,0.008411,True,False,100,"{'standardscaler__with_std': True, 'standardsc...",-50.835264,-47.727923,-48.077773,-49.137860,-49.650534,-49.085871,1.117337,5
10,0.010721,0.002401,0.535607,0.034205,True,True,464,"{'standardscaler__with_std': True, 'standardsc...",-57.843982,-55.159464,-56.264936,-56.829893,-56.752235,-56.570102,0.872520,9
11,0.008878,0.000572,0.012811,0.000707,False,True,21,"{'standardscaler__with_std': False, 'standards...",-86.690837,-83.375163,-86.128416,-84.837293,-85.112294,-85.228801,1.144525,11
12,0.009433,0.000327,0.325945,0.011969,True,False,215,"{'standardscaler__with_std': True, 'standardsc...",-53.679335,-50.753514,-51.390576,-52.339837,-52.472746,-52.127201,1.000337,6
13,0.009062,0.000127,0.862230,0.011468,True,True,1000,"{'standardscaler__with_std': True, 'standardsc...",-63.874015,-61.274555,-62.986133,-62.893518,-62.947273,-62.795099,0.842075,10
14,0.008730,0.000177,0.127328,0.003291,False,True,464,"{'standardscaler__with_std': False, 'standards...",-91.659617,-88.997754,-91.522955,-90.601130,-91.140565,-90.784404,0.965817,17
15,0.009047,0.000214,0.331496,0.010646,True,True,215,"{'standardscaler__with_std': True, 'standardsc...",-53.679335,-50.753514,-51.390576,-52.339837,-52.472746,-52.127201,1.000337,6
16,0.009000,0.000170,0.069344,0.005263,True,True,2,"{'standardscaler__with_std': True, 'standardsc...",-48.725569,-46.188053,-46.045258,-48.075274,-48.205757,-47.447982,1.109505,4
17,0.010012,0.001863,0.101560,0.004890,True,False,10,"{'standardscaler__with_std': True, 'standardsc...",-46.271824,-43.097111,-43.050352,-44.907051,-45.217594,-44.508787,1.256120,1
18,0.008850,0.000065,0.078976,0.004708,True,False,4,"{'standardscaler__with_std': True, 'standardsc...",-46.080299,-43.548209,-44.209090,-45.550981,-45.628370,-45.003390,0.959026,2
19,0.008446,0.000220,0.128680,0.001429,False,False,464,"{'standardscaler__with_std': False, 'standards...",-91.659617,-88.997754,-91.522955,-90.601130,-91.140565,-90.784404,0.965817,17